name: Block Critical File Deletions

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-deletions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: false

      - name: Get list of deleted files
        run: |
          git fetch origin dev
          git diff --name-status origin/dev...HEAD > changed_files.txt
          cat changed_files.txt

      - name: Warn if any file is deleted
        run: |
          if grep -E '^D\s+' changed_files.txt; then
            echo "⚠️ Warning: Some files were deleted in this PR:"
            grep -E '^D\s+' changed_files.txt | awk '{ print " - " $2 }'
            echo "Please double-check if these deletions are intentional."
          else
            echo "✅ No deletions detected."
          fi
